spring:
  profiles:
    active: ${PROFILE:local}
  application:
    name: library-service
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    open-in-view: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
server:
  servlet:
    context-path: /library-service
